config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"
  resources :questions, except: :edit
 
  resources :emails, only: [:new, :create]
 
  get 'answers/new/:user_id', to: 'answers#new', as: :new_answer
  post 'answer', to: 'answers#create', as: :answer
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions' 
  }
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true, length: { in: 2..50 }
  validates :user_id, presence: true

  belongs_to :user
  has_many :answers, dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @questions = current_user.questions.all
  end

  def new
    @questions = current_user.questions.all
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to new_question_path, success: "質問を作成しました"
    else
      @questions = current_user.questions.all
      render :new
    end
  end

  def show
    @question = Question.find_by(id: params[:id])
    @answers = @question.answers
  end

  def destroy
    question = Question.find_by(id: params[:id])
    if question.destroy
      redirect_to questions_path, success: "質問を削除しました"
    else
      flash.now[:alert] = "削除に失敗しました"
      render :index
    end
  end

  private 
  def question_params
    params.require(:question).permit(:content)
  end
end

app/views/questions/index.html.erb
<div class="home-title">
  <h2>マイページ</h2>
</div>
  <% if user_signed_in? %>
    <div class="user-name">
      <p><span>お名前: </span><%= current_user.user_name %></p>
    </div>
  <% end %>
  <div class="sub-menu">
    <div class="create-question">
      <%= link_to "", new_question_path, { class: "make-question fas fa-edit" } %>
    </div>
    <div class="create-email">
      <%= link_to "",new_email_path, { class: "make-email fas fa-envelope" } %>
    </div>
  </div>
  <div class="question-list">
    <% @questions.each do |question| %>
      <div class="question">
        <p class="content"><%= question.content %></p>
        <div class="answer_delete">
          <p class="answers"><%= link_to "回答", question_path(question), { class: "answer-button" } %></p>
          <p class="delete"><%= link_to "削除", question_path(question),{ method: :delete, class: "delete-button" } %></p>
        </div>
      </div>
    <% end %>
  </div>

app/views/questions/new.html.erb
<div class="home-title">
  <h2>新規作成</h2>
</div>

<div class="form-all">
  <div class="form-input" >
    <%= form_for @question do |f| %>
      <div class="form">
        <p class="form-label"><%= f.label :投稿%></p>
        <%= f.text_area :content, { class: "form-content" } %>
        <%= f.submit "作成" , { class: "form-question" }%>
      </div>
    <% end %>
  </div>

  <div class="new-questions-list">
    <% @questions.each do |question| %>
      <div class="new-questions">
        <li><%= question.content %></li>
      </div>
    <% end %>
  </div>

</div>

app/views/questions/show.html.erb
<div class="entire_question_show">
  <h2 class="question_show_title">回答一覧</h2>

  <p class="question_show_question"><%= @question.content %></p>
  <% @answers.each do |answer| %>
    <p class="content show_content"><%= answer.content %></p>
  <% end %>
</div>