config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"
  resources :questions, except: :edit
 
  resources :emails, only: [:new, :create]
 
  get 'answers/new/:user_id', to: 'answers#new', as: :new_answer
  post 'answer', to: 'answers#create', as: :answer
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions' 
  }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <div class="menu-bar">
        <%= link_to "Make Question", root_path, class: "title_in_menu" %>
        <% if user_signed_in? %>
          <div class="sub-menu-bar">
            <div class="menu-home">
              <%= link_to "ホーム", questions_path, { class: "home-alt" } %>
            </div>
            <div class="menu-logout">
              <%= link_to "ログアウト", destroy_user_session_path, { method: :delete, class: "sign-out-alt" } %>
            </div>
            <div class="menu-logout">
              <%= link_to "退会", user_registration_path, { method: :delete, data: { confirm: 'Are you sure?' }, class: "sign-out-alt alert-out" } %>
            </div>
          </div>
        <% end %>
      </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>

  <script>
    $(function(){
        $('.alert').fadeOut(3000);
    });
  </script>

</html>